module.exports = {
  id: 'light',
  label: 'Sakura Light',
  background: '#fff1f8',
  border: '#ffc5dd',
  panel: '#fffafd',
  panelBorder: '#ffc8df',
  divider: '#ffd6e7',
  text: '#261126',
  muted: '#9b5a79',
  subtle: '#da2d86',
  accent: '#e93487',
  accent2: '#ffd14f',
  accent3: '#c7a4ff',
  glow: '#ff8fad',
  shadow: '#f7cada',
  band: '#ffe8f2',
  band2: '#fff7fb',
  waveform: ['#ff9caf', '#ff7fa4', '#ffd052'],
}

